package com.codemagic.TrackMyMileage.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FILL_LOG.
 */
public class FillLog {

    /** Not-null value. */
    private java.util.Date fillDate;
    private double gallons;
    private Double pricePerGallon;
    private long curMiles;
    private long vehicleId;
    private Double mpg;

    public FillLog() {
    }

    public FillLog(java.util.Date fillDate, double gallons, Double pricePerGallon, long curMiles, long vehicleId, Double mpg) {
        this.fillDate = fillDate;
        this.gallons = gallons;
        this.pricePerGallon = pricePerGallon;
        this.curMiles = curMiles;
        this.vehicleId = vehicleId;
        this.mpg = mpg;
    }

    /** Not-null value. */
    public java.util.Date getFillDate() {
        return fillDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFillDate(java.util.Date fillDate) {
        this.fillDate = fillDate;
    }

    public double getGallons() {
        return gallons;
    }

    public void setGallons(double gallons) {
        this.gallons = gallons;
    }

    public Double getPricePerGallon() {
        return pricePerGallon;
    }

    public void setPricePerGallon(Double pricePerGallon) {
        this.pricePerGallon = pricePerGallon;
    }

    public long getCurMiles() {
        return curMiles;
    }

    public void setCurMiles(long curMiles) {
        this.curMiles = curMiles;
    }

    public long getVehicleId() {
        return vehicleId;
    }

    public void setVehicleId(long vehicleId) {
        this.vehicleId = vehicleId;
    }

    public Double getMpg() {
        return mpg;
    }

    public void setMpg(Double mpg) {
        this.mpg = mpg;
    }

}
