package com.codemagic.TrackMyMileageDB.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VEHICLE.
 */
public class Vehicle {

    private Long id;
    /** Not-null value. */
    private String vehicleName;
    /** Not-null value. */
    private String makeModel;
    private Integer year;
    private String engineType;

    public Vehicle() {
    }

    public Vehicle(Long id) {
        this.id = id;
    }

    public Vehicle(Long id, String vehicleName, String makeModel, Integer year, String engineType) {
        this.id = id;
        this.vehicleName = vehicleName;
        this.makeModel = makeModel;
        this.year = year;
        this.engineType = engineType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getVehicleName() {
        return vehicleName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVehicleName(String vehicleName) {
        this.vehicleName = vehicleName;
    }

    /** Not-null value. */
    public String getMakeModel() {
        return makeModel;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMakeModel(String makeModel) {
        this.makeModel = makeModel;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public String getEngineType() {
        return engineType;
    }

    public void setEngineType(String engineType) {
        this.engineType = engineType;
    }

}
